import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';

export default [
  // ── Never linted ────────────────────────────────────────────────────
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'coverage/**',
      // Generated by graphql-codegen in Module 10. Linting generated code is
      // pointless: you cannot fix it, and regenerationg would unde the fix
      'src/gql/**',
    ],
  },

  js.configs.recommended,

  // Type-aware rules. Sliwer than `recommended`, and worth it see §3.
  ...tseslint.configs.recommendedTypeChecked,

  {
    files: ['**/*.{ts,tsx,mts,mjs}'],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // A forgotten `await` on a GraphQL call is the bug this whole tier
      // exists to catch. Error, not warning.
      '@typescript-eslint/no-floating-promises': 'error',

      // `_`-prefixed args are intentionally unused (React event handlers,
      // catch bindings). Everything else is a mistake.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],

      // `any` defeats the entire point of Module 07. Use `unknown` and narrow.
      '@typescript-eslint/no-explicit-any': 'error',

      // `== null` is the one coercion worth keeping — it catches null AND
      // undefined in one test, which is the check you actually want. Lesson
      // 07.2 §8 promises this rule by name and permits exactly that form.
      eqeqeq: ['error', 'always', { null: 'ignore' }],

      // Stale suppressions are themselves errors. Scoped to this block, which is
      // the TS/TSX surface — so a stale disable inside the `**/*.graphql` block
      // Lesson 23.5 adds is NOT reported. Accepted: that block carries one rule.
      // Lesson 23.7 relies on this setting when it gives its selector-contract
      // rule a documented one-line escape hatch.
    },
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
    },
  },

  // Plain JS files are not in the TS project — turn type-aware rules off
  // for them rather than adding them to tsconfig. `**/` matters here since
  // e.g. scripts/blame.mjs is nested, not at the project root.
  {
    files: ['**/*.mjs', '**/*.js'],
    ...tseslint.configs.disableTypeChecked,
  },

  // ── React ─────────────────────────────────────────────────────────────
  // .ts as well as .tsx: a custom hook is a plain function in a .ts file, and
  // rules-of-hooks has to see it (Lesson 08.4 writes one).
  {
    files: ['**/*.{ts,tsx}'],
    plugins: { react, 'react-hooks': reactHooks },
    languageOptions: { parserOptions: { ecmaFeatures: { jsx: true } } },
    settings: { react: { version: 'detect' } },
    rules: {
      ...react.configs.flat.recommended.rules,

      // Off because `jsx: react-jsx` compiles JSX with no React import. These
      // two would fire on every component file in the project.
      'react/react-in-jsx-scope': 'off',
      'react/jsx-uses-react': 'off',

      // Off because TypeScript types the props. propTypes are the runtime
      // alternative and this project has a compile-time one.
      'react/prop-types': 'off',

      // Calling a hook conditionally breaks React's internal ordering. There is
      // no valid reason to do it, so: error.
      'react-hooks/rules-of-hooks': 'error',

      // The plugin ships this as a warning. `npm run lint` runs with
      // --max-warnings=0 (Lesson 07.5), so a warning already fails the build —
      // calling it a warning only hides which line is at fault.
      'react-hooks/exhaustive-deps': 'error',
    },
  },

  // The throwaway harness from Step 4 is outside tsconfig.json's `include`, so
  // the type-aware rules have no program to consult for it. Turn those off here
  // rather than adding a disposable directory to the type-check surface. The
  // syntactic rules, including rules-of-hooks, still apply. Lesson 09.1 deletes
  // the directory and this block with it.
  {
    files: ['scratch/**/*.{ts,tsx}'],
    ...tseslint.configs.disableTypeChecked,
  },

  // LAST. eslint-config-prettier only DISABLES rules, so anything after it
  // could re-enable a formatting rule and start a fight with Prettier.
  prettier,
];
