query HomepageFeeds($featuredCount: Int!, $recentCount: Int!) {
  catastrophic: incidents(first: $featuredCount, where: { status: PUBLISH }) {
    nodes {
      ...IncidentCardFields
    }
  }
  recent: incidents(first: $recentCount, where: { status: PUBLISH }) {
    nodes {
      ...IncidentCardFields
    }
  }
}

fragment IncidentCardFields on Incident {
  id
  title
  slug
  date
  severities(first: 1) {
    nodes {
      name
      slug
    }
  }
  scapegoats(first: 1) {
    nodes {
      name
      slug
    }
  }
  incidentDetails {
    downtimeMinutes
    environment
  }
}
