<?php

/**
 * SCF integration: Local JSON paths, admin visibility, and field-level rules.
 *
 * Field DEFINITIONS live in includes/acf-json/ and are tracked in git.
 * Field VALUES live in wp_postmeta / wp_termmeta and are not.
 *
 * @package Blame\Core
 */

declare(strict_types=1);

namespace Blame\Core;

defined('ABSPATH') || exit;

/**
 * The one directory SCF writes field groups to, and the one this plugin reads
 * them from. Inside the plugin, so it ships in the Module 24 container image.
 */
const SCF_JSON_DIR = PLUGIN_DIR . '/includes/acf-json';


add_filter('acf/settings/save_json', __NAMESPACE__ . '\\acf_json_save_path');
add_filter('acf/settings/load_json', __NAMESPACE__ . '\\acf_json_load_paths');
add_filter('acf/json/save_file_name', __NAMESPACE__ . '\\acf_json_file_name', 10, 3);
add_filter('acf/settings/show_admin', __NAMESPACE__ . '\\acf_show_admin');
add_filter('acf/prepare_field/name=is_verified', __NAMESPACE__ . '\\hide_verified_from_reporters');
add_action('admin_notices', __NAMESPACE__ . '\\acf_json_writability_notice');


/**
 * Where SCF SAVES a field group. Returns a single directory (a string).
 *
 * Falls back to whatever SCF proposed if our directory is missing, so a broken
 * checkout degrades to SCF's default rather than throwing away the save.
 *
 * @param string $path SCF's default — the active theme's acf-json directory.
 */
function acf_json_save_path(string $path): string
{
	return is_dir(SCF_JSON_DIR) ? SCF_JSON_DIR : $path;
}

/**
 * Where SCF LOADS field groups from. Receives — and returns — an ARRAY.
 *
 * SCF's default entry is the active theme. The `btt-headless` theme is a
 * redirect stub that owns no part of the content model (Lesson 03.1 Key
 * Concept 1), so it is removed by value rather than by index: another plugin
 * may legitimately have added a path before us.
 *
 * @param string[] $paths Directories SCF will scan for *.json.
 * @return string[]
 */
function acf_json_load_paths(array $paths): array
{
	$theme_dir = get_stylesheet_directory() . '/acf-json';

	$paths = array_values(
		array_filter(
			$paths,
			static fn(string $path): bool => $path !== $theme_dir
		)
	);

	$paths[] = SCF_JSON_DIR;

	return $paths;
}

/**
 * Name the file after the group TITLE instead of its key.
 *
 * SCF's default filename is "{$key}.json", and a key generated by the UI looks
 * like `group_663f2a1b4c5d6` — unreadable in a file list and worse in a diff.
 *
 * The trade: renaming a field group renames its file, and the old file is left
 * behind. `git status` shows the new one as untracked; delete the stale one in
 * the same commit.
 *
 * @param string               $filename  SCF's proposed filename.
 * @param array<string, mixed> $post      The field group being saved.
 * @param string               $load_path The directory it is being written to.
 */
function acf_json_file_name(string $filename, array $post, string $load_path): string
{
	$slug = str_replace('-', '_', sanitize_title((string) ($post['title'] ?? '')));

	return '' === $slug ? $filename : 'group_' . $slug . '.json';
}

/**
 * Hide the field-group builder in production.
 *
 * There is nothing to build there: definitions arrive as JSON with the code,
 * and an edit made in production would be overwritten by the next deploy.
 *
 * @param bool $show SCF's default, true.
 */
function acf_show_admin(bool $show): bool
{
	return $show && 'production' !== wp_get_environment_type();
}

/**
 * Remove `is_verified` from the form for anyone who cannot moderate.
 *
 * Returning FALSE removes the field entirely, so it never appears in
 * $_POST['acf'] and SCF never writes it. Setting `disabled` instead would let
 * the True/False field's hidden `0` input post anyway, and pressing Update
 * would silently un-verify the incident. See Key Concept 7.
 *
 * @param array<string, mixed>|false $field The prepared field, or false.
 * @return array<string, mixed>|false
 */
function hide_verified_from_reporters(array|false $field): array|false
{
	return current_user_can('edit_others_incidents') ? $field : false;
}

/**
 * One admin notice for the one environment problem this setup has.
 *
 * The plugin directory is a bind mount owned by your host user; PHP in the
 * container runs as www-data. On Docker Desktop that is papered over. On Linux
 * it is not, and SCF silently stops emitting JSON.
 */
function acf_json_writability_notice(): void
{
	if (! current_user_can('manage_options') || ! function_exists('acf_get_setting')) {
		return;
	}

	if (is_dir(SCF_JSON_DIR) && wp_is_writable(SCF_JSON_DIR)) {
		return;
	}

	printf(
		'<div class="notice notice-warning"><p><strong>%s</strong> %s <code>%s</code></p></div>',
		esc_html__('SCF Local JSON is not writable.', 'blame-the-tech-core'),
		esc_html__('Field group saves will go to the database instead. Fix the directory, then run:', 'blame-the-tech-core'),
		esc_html('sudo chown -R 33:33 includes/acf-json')
	);
}
