services:
  wordpress:
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_HOME', getenv('WP_HOME') );
        define( 'WP_SITEURL', getenv('WP_SITEURL') );
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_DEBUG_DISPLAY', false );
        define( 'SCRIPT_DEBUG', true );
        define( 'WP_ENVIRONMENT_TYPE', 'local' );

  db:
    ports:
      - "3306:3306"
